name: Keep Supabase Alive

# This tells GitHub when to run the bot
on:
  schedule:
    # Runs at midnight every Monday and Thursday
    - cron: "0 0 * * 1,4"
  workflow_dispatch: # This allows you to click a button to run it manually

jobs:
  ping-database:
    runs-on: ubuntu-latest
    steps:
      - name: Make API call to Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        # This acts like UptimeRobot, but specifically makes a database read request
        run: |
          curl "$SUPABASE_URL/rest/v1/Users?select=id&limit=1" \
          -H "apikey: $SUPABASE_KEY" \
          -H "Authorization: Bearer $SUPABASE_KEY"
